apiVersion: v1
kind: Service
metadata:
  name: vpa-recommender
  namespace: kube-system
  labels:
    app: vpa-recommender
spec:
  selector:
    app: vpa-recommender
  ports:
    - name: metrics
      port: 8942
      targetPort: 8942
